name: Deploy grönsås.life
on:
  push:
    branches:
      - main
jobs:
  Build-And-Deploy-Website:
    runs-on: self-hosted
    environment:
      name: Deployment
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: valderman/mat:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
